<template>
    <div id="kt_content_container" class="container-xxl">
        <div class="card card-flush mt-5">
            <!-- Header -->
            <div class="card-header border-0 pt-6">
                <div class="card-title">
                    <div class="d-flex align-items-center position-relative my-1">
                        <i class="fa fa-robot fs-1 text-primary me-3"></i>
                        <h3 class="fw-bolder">AI-Powered Financial Insights</h3>
                    </div>
                </div>
                <div class="card-toolbar">
                    <button 
                        @click="aiStore.fetchInsights(true)" 
                        class="btn btn-sm btn-light-primary"
                        :disabled="aiStore.loading"
                    >
                        <i v-if="!aiStore.loading" class="fa fa-sync me-2"></i>
                        <span v-else class="spinner-border spinner-border-sm me-2"></span>
                        Refresh Insights
                    </button>
                </div>
            </div>

            <!-- Body -->
            <div class="card-body pt-0">
                <div v-if="aiStore.loading && !aiStore.insight" class="d-flex flex-column align-items-center py-20">
                    <div class="spinner-border text-primary w-40px h-40px mb-5" role="status"></div>
                    <span class="text-muted fw-bold">Gemini is analyzing your finances...</span>
                </div>

                <div v-else-if="aiStore.error" class="alert alert-danger d-flex align-items-center p-5 mb-10">
                    <i class="fa fa-exclamation-triangle fs-2hx text-danger me-4"></i>
                    <div class="d-flex flex-column">
                        <h4 class="mb-1 text-danger">Insight Error</h4>
                        <span>{{ aiStore.error }}</span>
                    </div>
                </div>

                <div v-else-if="aiStore.insight" class="insight-content py-5">
                    <div class="p-8 bg-light-primary rounded-3 border border-primary border-dashed mb-8">
                        <div class="fs-4 text-gray-800" v-html="renderedMarkdown"></div>
                    </div>
                    
                    <div class="text-muted fs-7 text-center">
                        Generated by Google Gemini 1.5 Flash. Insights are based on historical data.
                    </div>
                </div>

                <div v-else class="text-center py-20">
                    <div class="mb-5">
                        <i class="fa fa-brain fs-5x text-light-dark opacity-25"></i>
                    </div>
                    <h3 class="text-muted">No insights generated yet</h3>
                    <button @click="aiStore.fetchInsights()" class="btn btn-primary mt-5">Generate First Insight</button>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { onMounted, computed } from 'vue';
import { useAIInsightStore } from '@/stores/aiInsight';
import { marked } from 'marked';
import { initializeAppPlugins } from '@/plugins/global';

const aiStore = useAIInsightStore();

const renderedMarkdown = computed(() => {
    return aiStore.insight ? marked(aiStore.insight) : '';
});

onMounted(() => {
    initializeAppPlugins();
    if (!aiStore.insight) {
        aiStore.fetchInsights();
    }
});
</script>

<style scoped>
.insight-content :deep(h1), 
.insight-content :deep(h2), 
.insight-content :deep(h3) {
    font-weight: 700;
    margin-top: 1.5rem;
    margin-bottom: 1rem;
    color: var(--bs-gray-900);
}

.insight-content :deep(ul) {
    padding-left: 1.5rem;
    margin-bottom: 1.5rem;
}

.insight-content :deep(li) {
    margin-bottom: 0.5rem;
}

.insight-content :deep(p) {
    margin-bottom: 1rem;
    line-height: 1.6;
}

.insight-content :deep(strong) {
    color: var(--bs-primary);
}
</style>
